### ISSUE TITLE
PR #2537 segfaults

### ISSUE THREAD

**Issue by higaski** [kisvegabor/lvgl#2619]
### Describe the bug
The latest commit which merges PR #2537 segfaults my code when using multiple btnmatrix widgets inside a grid layout.

### To Reproduce

```c
  lv_coord_t col_dsc[] = {LV_GRID_FR(10), LV_GRID_FR(2), LV_GRID_TEMPLATE_LAST};
  lv_coord_t row_dsc[] = {LV_GRID_FR(10), LV_GRID_FR(2), LV_GRID_TEMPLATE_LAST};

  char const* func_map[] = {
    "F0",  "F1",  "F2",  "\n",  "F3",  "F4",  "F5",  "\n",  "F6",  "F7",
    "F8",  "\n",  "F9",  "F10", "F11", "\n",  "F12", "F13", "F14", "\n",
    "F15", "F16", "F17", "\n",  "F18", "F19", "F20", "\n",  "F21", "F22",
    "F23", "\n",  "F24", "F25", "F26", "\n",  "F27", "F28", "F29", ""};
  char const* reed_mn_map[] = {"IN1", "IN2", "IN3", "IN4", "MN", ""};

  lv_obj_t* parent = lv_scr_act();
  lv_obj_set_style_grid_column_dsc_array(parent, col_dsc, 0u);
  lv_obj_set_style_grid_row_dsc_array(parent, row_dsc, 0u);
  lv_obj_set_layout(parent, LV_LAYOUT_GRID);

  lv_obj_t* func_btnm = lv_btnmatrix_create(parent);
  lv_btnmatrix_set_map(func_btnm, func_map);

  lv_obj_t* reed_mn_btnm = lv_btnmatrix_create(parent);
  lv_btnmatrix_set_map(reed_mn_btnm, reed_mn_map);

  lv_obj_set_grid_cell(
    func_btnm, LV_GRID_ALIGN_STRETCH, 0u, 1u, LV_GRID_ALIGN_STRETCH, 0u, 1u);
  lv_obj_set_grid_cell(
    reed_mn_btnm, LV_GRID_ALIGN_STRETCH, 0u, 1u, LV_GRID_ALIGN_STRETCH, 1u, 1u);
```

GDB backtrace
```
#0  0x0000555555954743 in block_size (block=0x69559c56244aa4) at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/misc/lv_tlsf.c:383
#1  0x00005555559547af in block_is_last (block=0x69559c56244aa4) at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/misc/lv_tlsf.c:394
#2  0x00005555559561b5 in lv_tlsf_walk_pool (pool=0x555555e02af8 <work_mem_int+3416>, walker=0x555555955a85 <integrity_walker>, user=0x7fffffffd6e0) at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/misc/lv_tlsf.c:899
#3  0x0000555555956247 in lv_tlsf_check_pool (pool=0x555555e02af8 <work_mem_int+3416>) at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/misc/lv_tlsf.c:923
#4  0x000055555594fad7 in lv_mem_test () at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/misc/lv_mem.c:219
#5  0x000055555592c3ff in calc (cont=0x555555e03dc0 <work_mem_int+8224>, calc_out=0x7fffffffd7c0) at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/extra/layouts/grid/lv_grid.c:418
#6  0x000055555592c047 in grid_update (cont=0x555555e03dc0 <work_mem_int+8224>, user_data=0x0) at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/extra/layouts/grid/lv_grid.c:354
#7  0x000055555590cc06 in layout_update_core (obj=0x555555e03dc0 <work_mem_int+8224>) at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/core/lv_obj_pos.c:963
#8  0x0000555555909aac in lv_obj_update_layout (obj=0x555555e03dc0 <work_mem_int+8224>) at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/core/lv_obj_pos.c:306
#9  0x0000555555915f05 in _lv_disp_refr_timer (tmr=0x555555e02d80 <work_mem_int+4064>) at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/core/lv_refr.c:200
#10 0x00005555559545ea in lv_timer_exec (timer=0x555555e02d80 <work_mem_int+4064>) at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/misc/lv_timer.c:315
#11 0x00005555559541a5 in lv_timer_handler () at /home/vinci/Develop/VSCode/MSlvgl/build/_deps/lvgl-src/src/misc/lv_timer.c:106
#12 0x00005555555898f6 in main(int, char**) (argc=2, argv=0x7fffffffdc48) at /home/vinci/Develop/VSCode/MSlvgl/src/main.cpp:69
```

### Expected behavior
Up until 480ee77911a254fea11f37bb43c22930b963887b the posted snippet worked fine.

### Screenshots or video
![Screenshot_MSlvgl_2](https://user-images.githubusercontent.com/13762516/135254185-90200f79-4505-476a-9a00-44939868fca4.png)

**Comment by kisvegabor** [comment]
Thanks for the report. It was an issue in the button matrix.
