### ISSUE TITLE
Lv_snapshot_take is leading to segmentation fault

### ISSUE THREAD

**Issue by mahesh-slx** [kisvegabor/lvgl#5130]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I’m using LVGL v8.3.10 with simulator in linux system. I have changed the LV_USE_SNAPSHOT to 1 and I’m allocating memory of LV_MEM_SIZE (8192 * 1024U) in lv_conf.h file. when I call the function lv_snapshot_take() I am running into segmentation fault.I debugged the code by using gdb and the problem is, the display driver user data is pointing to null. And while trying to dereference it and accessing renderer object the segmentation fault is happening. During the initialization of display driver, the display driver user data is not pointing to null.

### To Reproduce

```c
The cap function is called once inside the while loop which is present inside main function as shown below.

bool flg_once = false;
static void hal_init(void);
void cap()
{
  lv_obj_t * src = lv_scr_act(); // Get the active screen
  lv_img_dsc_t * snapshot = NULL;
  snapshot = lv_snapshot_take(src, LV_IMG_CF_TRUE_COLOR_ALPHA);
  if(snapshot == NULL ){
    printf(“Failed to take snapshot\n”);
    return;
  }
  else
  {
     printf(“ Snapshot taken successfully\n”);
      return;
  }
}

int main(int argc, char **argv) {
  (void)argc; /*Unused*/
  (void)argv; /*Unused*/

  /*Initialize LVGL*/
  lv_init();

  /*Initialize the HAL (display, input devices, tick) for LVGL*/
  hal_init();

  while (1) {
    lv_timer_handler();
    process_request(100);
    usleep(5 * 1000);
    if(flg_once == false){
      cap();
      flg_once = true;
    }
  }
}

/**
 * Initialize the Hardware Abstraction Layer (HAL) for the LVGL graphics
 * library
 */
static void hal_init(void) {
  /* Use the 'monitor' driver which creates window on PC's monitor to simulate a
   * display*/
  sdl_init();
  /* Tick init.
   * You have to call 'lv_tick_inc()' in periodically to inform LittelvGL about
   * how much time were elapsed Create an SDL thread to do this*/
  SDL_CreateThread(tick_thread, "tick", NULL);

  /*Create a display buffer*/
  static lv_disp_draw_buf_t disp_buf1;
  static lv_color_t buf1_1[SDL_HOR_RES * 100];
  static lv_color_t buf1_2[SDL_VER_RES * 100];
  lv_disp_draw_buf_init(&disp_buf1, buf1_1, buf1_2, SDL_HOR_RES * 100);

  /*Create a display*/
  static lv_disp_drv_t disp_drv;
  lv_disp_drv_init(&disp_drv); /*Basic initialization*/
  disp_drv.draw_buf = &disp_buf1;
  disp_drv.flush_cb = sdl_display_flush;
  disp_drv.hor_res = SDL_HOR_RES;
  disp_drv.ver_res = SDL_VER_RES;
  sdl_disp_drv_init(&disp_drv, SDL_HOR_RES, SDL_VER_RES);
  lv_disp_t *disp = lv_disp_drv_register(&disp_drv);

  // lv_theme_t *th = lv_theme_default_init(
  //     disp, lv_palette_main(LV_PALETTE_BLUE),
  //     lv_palette_main(LV_PALETTE_RED), LV_THEME_DEFAULT_DARK,
  //     LV_FONT_DEFAULT);
  // lv_disp_set_theme(disp, th);

  lv_group_t *g = lv_group_create();
  lv_group_set_default(g);

  /* Add the mouse as input device
   * Use the 'mouse' driver which reads the PC's mouse*/
  // mouse_init();
  static lv_indev_drv_t indev_drv_1;
  lv_indev_drv_init(&indev_drv_1); /*Basic initialization*/
  indev_drv_1.type = LV_INDEV_TYPE_POINTER;

  /*This function will be called periodically (by the library) to get the mouse
   * position and state*/
  indev_drv_1.read_cb = sdl_mouse_read;
  lv_indev_t *mouse_indev = lv_indev_drv_register(&indev_drv_1);

  // keyboard_init();
  static lv_indev_drv_t indev_drv_2;
  lv_indev_drv_init(&indev_drv_2); /*Basic initialization*/
  indev_drv_2.type = LV_INDEV_TYPE_KEYPAD;
  indev_drv_2.read_cb = sdl_keyboard_read;
  lv_indev_t *kb_indev = lv_indev_drv_register(&indev_drv_2);
  lv_indev_set_group(kb_indev, g);
  // mousewheel_init();
  static lv_indev_drv_t indev_drv_3;
  lv_indev_drv_init(&indev_drv_3); /*Basic initialization*/
  indev_drv_3.type = LV_INDEV_TYPE_ENCODER;
  indev_drv_3.read_cb = sdl_mousewheel_read;

  lv_indev_t *enc_indev = lv_indev_drv_register(&indev_drv_3);
  lv_indev_set_group(enc_indev, g);

  /*Set a cursor for the mouse*/
  LV_IMG_DECLARE(mouse_cursor_icon); /*Declare the image file.*/
  lv_obj_t *cursor_obj =
      lv_img_create(lv_scr_act()); /*Create an image object for the cursor */
  lv_img_set_src(cursor_obj, &mouse_cursor_icon); /*Set the image source*/
  lv_indev_set_cursor(mouse_indev,
                      cursor_obj); /*Connect the image  object to the driver*/
}

```

### Expected behavior

Expect it to print either snapshot sucess message or snapshot failure message

### Screenshots or video

Image related to stack backtrace when the segmentation fault occurred during debugging with gdb.
![stack_backtrace_lv_snapshot_take](https://github.com/lvgl/lvgl/assets/151005582/3bf57ceb-03bc-4cd1-8a3d-344516fa1ff7)

```
Thread 1 "demo" received signal SIGSEGV, Segmentation fault.
lv_draw_sdl_init_ctx (disp_drv=0x7fffffffdcb0, draw_ctx=0x555555789540 <work_mem_int+13824>) at /home/mahesh/.arduino15/internal/lvgl_8.3.10_b2d968ea6cc04576/lvgl/src/draw/sdl/lv_draw_sdl.c:78
78	    draw_ctx_sdl->renderer = ((lv_draw_sdl_drv_param_t *) disp_drv->user_data)->renderer;
(gdb) backtrace
#0  lv_draw_sdl_init_ctx (disp_drv=0x7fffffffdcb0, draw_ctx=0x555555789540 <work_mem_int+13824>)
    at /home/mahesh/.arduino15/internal/lvgl_8.3.10_b2d968ea6cc04576/lvgl/src/draw/sdl/lv_draw_sdl.c:78
#1  0x00005555555d5efa in lv_snapshot_take_to_buf (obj=0x555555789028 <work_mem_int+12520>, cf=5 '\005', dsc=0x555555789520 <work_mem_int+13792>, 
    buf=0x5555557926b0 <work_mem_int+51056>, buff_size=921600)
    at /home/mahesh/.arduino15/internal/lvgl_8.3.10_b2d968ea6cc04576/lvgl/src/extra/others/snapshot/lv_snapshot.c:134
#2  0x00005555555d61e8 in lv_snapshot_take (obj=0x555555789028 <work_mem_int+12520>, cf=5 '\005')
    at /home/mahesh/.arduino15/internal/lvgl_8.3.10_b2d968ea6cc04576/lvgl/src/extra/others/snapshot/lv_snapshot.c:182
#3  0x000055555555b8f4 in cap () at main.cpp:141
#4  0x000055555555b8c0 in main (argc=1, argv=0x7fffffffe0b8) at main.cpp:119
(gdb) print disp_drv
$1 = (lv_disp_drv_t *) 0x7fffffffdcb0
(gdb) print disp_drv->user_data
$2 = (void *) 0x0

```

**Comment by kisvegabor** [comment]
You are using the SDL renderer (not SW renderer with an SDL window as target). With this LVGL can't take a snapshot as SDL works with Textures not available reading. So we can't convert them to simple arrays.
