### ISSUE TITLE
Docs build break

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#6309]
### LVGL version

master

### What happened?

After this commit: https://github.com/lvgl/lvgl/commit/7addc72735e06b5c78af5638190f1c32b5bad426, the compilation of the document will fail.
I tried to remove the `lvgl/src/libs/thorvg/rapidjson` directory and the problem disappeared. I guess there is a problem with the `rapidjson` header file parsing. Can we bypass the `rapidjson` document parsing?

### How to reproduce?

```bash
./docs/build.py

****************
Building
****************
Generate the list of examples
Add translation
Running doxygen

cd "/tmp/tmpvn37sc3i.lvgl_docs" && doxygen Doxyfile
-------------------------------------
Reading Doxygen output
Traceback (most recent call last):
  File "/lvgl/./docs/build.py", line 147, in <module>
    doc_builder.run(
  File "/lvgl/docs/doc_builder.py", line 663, in run
    globals()[compound.attrib['kind'].upper()](
  File "/lvgl/docs/doc_builder.py", line 494, in __init__
    cls = globals()[member.attrib['kind'].upper()]
KeyError: 'FRIEND'
```

**Comment by FASTSHIFT** [comment]
See https://github.com/lvgl/lvgl/issues/6262
